#image_root: '/home/kyueran/caption-generation/shared_data/flickr30k/flickr30k_images'
#ann_root: 'annotation'
image_root: '/home/kyueran/caption-generation/BLIP-2/annotation/merlion_mod/output_folder_front'
ann_root: '/home/kyueran/caption-generation/BLIP-2/annotation/output'
coco_gt_root: 'annotation/flickr30k_gt'

# set pretrained as a file path or an url
pretrained: '/home/kyueran/caption-generation/BLIP-2/configs/weights/merlion-distil-0.pth'
#pretrained: 'https://storage.googleapis.com/sfr-vision-language-research/BLIP/models/model_base_caption_capfilt_large.pth'

# size of vit model; base or large
vit: 'base'
vit_grad_ckpt: False
vit_ckpt_layer: 0
batch_size: 4
init_lr: 1e-5

# vit: 'large'
# vit_grad_ckpt: True
# vit_ckpt_layer: 5
# batch_size: 16
# init_lr: 2e-6

image_size: 384

# generation configs
max_length: 200
min_length: 20
num_beams: 3
prompt: 'a picture of '

# optimizer
weight_decay: 0.05
min_lr: 0
max_epoch: 1

